name: '${project.name}'
version: '${project.version}'
main: com.TechnicJelle.BlueMapTimeMarker.BlueMapTimeMarker
api-version: 1.13
depend:
  - BlueMap
author: TechnicJelle
description: '${project.description}'
website: '${project.url}'
